services:
  fast-gaz-ui:
    container_name: fastgaz-frontend
    build: .
    image: dongmomartial/fastgaz-frontend:v1.0.0
    restart: unless-stopped
    depends_on:
      - fast-gaz-api
    ports:
      - 30003:80
      - 30004:443
    expose:
      - 30003
      - 30004
    volumes:	
      - /nginx.conf 
      - /etc/letsencrypt/live/kapexpert.cloud/fullchain.pem:/etc/letsencrypt/live/kapexpert.cloud/fullchain.pem
      - /etc/letsencrypt/live/kapexpert.cloud/privkey.pem:/etc/letsencrypt/live/kapexpert.cloud/privkey.pem
    networks:
      - networks-fastgaz

  fast-gaz-api:
    container_name: fast-gaz-api
    image: dongmomartial/fastgaz-backend:v1.0.0
    ports:
      - 8087:8087
    environment:
      SPRING_APPLICATION_JSON: '{
            "server.ssl.key-store" : "classpath:keystore/letsencrypt.jks",
            "server.ssl.key-store-type" : "PKCS12",
            "server.ssl.key-alias" : "letsencrypt",
            "server.ssl.key-store-password" : "changeit", 
            "server.ssl.enabled" : "true",
            "spring.datasource.url"  : "jdbc:postgresql://195.231.19.75:5432/fastgazdbprod",
            "spring.datasource.username" : "itacadminpro2024",
            "spring.datasource.password" : "DIOewdVh18n350",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "create-drop",
            "spring.profiles.active" : "prod"
          }'
    networks:
      - networks-fastgaz
    restart: unless-stopped


networks:
  networks-fastgaz:
    driver: bridge
volumes:
  networks-fastgaz:

